# hparams to sweep
learning_rate: 5e-5
max_duration: 1
weight_decay: 5e-6
device_train_microbatch_size: 64
task: mrpc
metric_to_monitor: MulticlassAccuracy


max_seq_len: 512
save_num_checkpoints_to_keep: 1

# Whether to run the various GLUE jobs serially or in parallel (use parallel=True to take advantage of multiple GPUs)
parallel: false

# Basic run configuration, additional details will be added to this name for each GLUE task, and each random seed
base_run_name: decoder-base-deterministic
default_seed: 19
precision: amp_bf16

# Tokenizer for dataset creation
tokenizer_name: bclavie/olmo_bert_template

# Base model config
model:
  name: hf_bert
  use_pretrained: true
  pretrained_model_name: microsoft/MiniLM-L12-H384-uncased
  tokenizer_name: ${tokenizer_name}

# Saving
save_finetune_checkpoint_prefix: baseline_eval_results/${task}
save_finetune_checkpoint_folder: ${save_finetune_checkpoint_prefix}/${base_run_name}

# (Optional) W&B logging
loggers:
  wandb:
    project: sweeps
    entity: mmarone-jhu

# Callbacks
callbacks:
  lr_monitor: {}
  speed_monitor: {}
  early_stopper: 
    task: ${task}
    metric_to_monitor: ${metric_to_monitor}

# Scheduler
scheduler:
  name: linear_decay_with_warmup
  t_warmup: 0.06dur
  alpha_f: 0.0

# Scheduler
optimizer:
  name: decoupled_adamw
  lr: ${learning_rate}
  betas:
  - 0.9
  - 0.98
  eps: 1.0e-06
  weight_decay: ${weight_decay}
  filter_bias_norm_wd: true
  log_grad_norm: true
  

# Task configuration
tasks:
  abc:
    seeds:
    - 42
    trainer_kwargs:
      save_num_checkpoints_to_keep: ${save_num_checkpoints_to_keep}
      max_sequence_length: ${max_seq_len}
      max_duration: ${max_duration}
      batch_size: ${device_train_microbatch_size}
      save_overwrite: true