data_local: /brtx/archive/orionw/our_bert24/bert24/our_data/
data_remote: # If blank, files must be present in data_local

max_seq_len: 1024
tokenizer_name: bert-base-uncased
mlm_probability: 0.0 # FlexBERT should use 30% masking for optimal performance
count_padding_tokens: false

# Run Name
run_name: no_op_model_for_data
data_save_folder: data_order/

# Model
model:
  name: flex_noop
  pretrained_model_name: bert-base-uncased
  tokenizer_name: ${tokenizer_name}
  disable_train_metrics: true
  # FlexBERT 'base' generally uses the default architecture values from the Hugging Face BertConfig object
  # Note: if using the pretrained_checkpoint argument to create a model from an existing checkpoint, make sure
  # the model_config settings match the architecture of the existing model
  model_config:
    skip_all: true    


# Dataloaders
train_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: train
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: true
    mlm_probability: ${mlm_probability}
    streaming: false
    use_decoder_attn_mask: true
    shuffle_seed: 21
    suppress_masking: true
  drop_last: true
  num_workers: 10
  sequence_packing: false
  batch_size_warmup_min_size: ${device_train_microbatch_size}
  batch_size_warmup_tokens: 0tok


eval_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: 
    split: validation
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: false
    mlm_probability: 0.0 # We always evaluate at 15% masking for consistent comparison
    streaming: false
    use_decoder_attn_mask: true
    suppress_masking: true
  drop_last: false
  num_workers: 3
  sequence_packing: false


# Optimization
scheduler:
  name: warmup_stable_decay
  t_warmup: 4_000_000_000tok # Warmup to the full LR for 6% of the training duration
  alpha_f: 0.02 # Linearly decay to 0.02x the full LR by the end of the training duration
  t_decay: 0tok

optimizer:
  name: decoupled_stableadamw
  lr: 3e-3 # Peak learning rate
  betas:
  - 0.9
  - 0.98
  eps: 1.0e-06
  weight_decay: 3.0e-4 # Amount of weight decay regularization
  filter_bias_norm_wd: true # If True, doesn't apply weight decay to norm layers and biases
  log_grad_norm: true

max_duration: 1_700_000_000_000tok
eval_interval: 99999999999999999999999999999999ba # don't do this
global_train_batch_size: 4608
global_eval_batch_size: 1024

# System
seed: 21
device_eval_batch_size: 4608
device_train_microbatch_size: 4608

precision: FP32

# Logging
progress_bar: true
log_to_console: true
console_log_interval: 100ba

callbacks:
  speed_monitor:
    window_size: 100
  lr_monitor: {}
  scheduled_gc: {}
  log_grad_norm:
    batch_log_interval: 100
  packing_efficiency:
    log_interval: 100
  # hf_dataset_saver: {}
  optimized_data_saver: {}
  # batch_saver: {}
  # step_folder: {}
 
# W&B logging
loggers:
  wandb:
    project: data_gathering
    entity: mmarone-jhu

# Checkpoint to local filesystem or remote object store
save_interval: 8_500_000_000tok
save_num_checkpoints_to_keep: 100000  # Important, this cleans up checkpoints saved to DISK
save_folder: saved_folders_null_delete_me

# Load from local filesystem or remote object store to
# load_path: null

autoresume: true